CREATE DATABASE QLDIEM

USE QLDIEM

CREATE TABLE DMKHOA
(
 MAKHOA CHAR(2)PRIMARY KEY NOT NULL,
 TENKHOA NVARCHAR(25),
)
CREATE TABLE DMSV
(
 MASV CHAR(3) PRIMARY KEY NOT NULL,
 HOSV NVARCHAR(30),
TENSV NVARCHAR(20),
PHAI INT,
NGAYSINH DATETIME,
NOISINH NVARCHAR(25),
MAKH CHAR(2),
HOCBONG FLOAT,
)
CREATE TABLE KETQUA
(
	MASV CHAR(3) PRIMARY KEY NOT NULL,
	 MAMH  CHAR(2),
	LANTHI INT ,
	DIEM DECIMAL(4,2),
	
)
ALTER TABLE KETQUA ADD CONSTRAINT NAMH1 PRIMARY KEY(MAMH)	



 
